version: '3'

services:
  flask-app:
    build:
      context: .
    ports:
      - "80:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/flaskdb

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: flaskdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
